name: SyncthingTray
options:
  deploymentTarget:
    macOS: "14.0"
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.9.6"
settings:
  base:
    PRODUCT_NAME: "Syncthing Tray"
    PRODUCT_MODULE_NAME: SyncthingTray
    SWIFT_VERSION: "6.0"
    ARCHS: [arm64, x86_64]
schemes:
  SyncthingTray:
    build:
      targets:
        SyncthingTray: all
        SyncthingTrayTests: [test]
    test:
      targets:
        - SyncthingTrayTests
targets:
  SyncthingTray:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: SyncthingTray
        excludes:
          - "*.entitlements"
    dependencies:
      - package: Sparkle
        product: Sparkle
        embed: true
    info:
      path: SyncthingTray/Info.plist
      properties:
        CFBundleDisplayName: "Syncthing Tray"
        CFBundleShortVersionString: "1.0.1"
        CFBundleVersion: "2"
        LSUIElement: true
        NSPrincipalClass: NSApplication
        SUFeedURL: https://github.com/bstone108/Syncthing-Swift-Tray/releases/download/appcast/appcast.xml
        SUPublicEDKey: "QHiOcnw56iErvFKk231vGIdpsduIG/Rj/ygx+3Cn87E="
        SUEnableAutomaticChecks: true
        SUScheduledCheckInterval: 172800
        SUAutomaticallyUpdate: true
        SUShowReleaseNotes: false
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_BUNDLE_IDENTIFIER: com.brandonstone.syncthingtray
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: SyncthingTray/SyncthingTray.entitlements
        DEVELOPMENT_TEAM: K6N4J68LTY
        ENABLE_DEBUG_DYLIB: NO
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: NO
  SyncthingTrayTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: SyncthingTrayTests
    dependencies:
      - target: SyncthingTray
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_MODULE_NAME: SyncthingTrayTests
        PRODUCT_NAME: SyncthingTrayTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Syncthing Tray.app/Contents/MacOS/Syncthing Tray"
        BUNDLE_LOADER: "$(TEST_HOST)"
